"""Migración inicial aplanada

Revision ID: 91287cce8fa1
Revises: 
Create Date: 2025-08-05 06:51:15.639625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91287cce8fa1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resumen_ia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('apellido', sa.String(length=150), nullable=False),
    sa.Column('domicilio', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('dni', sa.String(length=20), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('barrio', sa.Enum('645_viviendas', '2_de_abril', '10_de_diciembre', '28_de_abril', '60_viviendas', '400_viviendas', 'aldea_del_este', 'arrayanes', 'barrio_el_pilar_i', 'barrio_el_pilar_ii', 'barrio_el_pilar_iii', 'barrio_jockey_club', 'barrio_nahuel_hue', 'barrio_vivero', 'barrio_vuriloche', 'belgrano', 'belgrano_sudeste', 'casa_de_piedra_ruca_cura', 'carihue', 'cerro_chico', 'coop_258', 'covibar', 'el_condor', 'el_faldeo', 'el_frutillar', 'el_maiten', 'el_mirador', 'el_progreso', 'gastronomico_2_de_agosto', 'islas_malvinas', 'jardin_botanico', 'jockey_club', 'la_cumbre', 'la_cascada', 'la_colina', 'las_margaritas', 'las_quintas', 'las_vertientes', 'las_victorias', 'levalle', 'los_cipresales', 'los_maitenes', 'los_retamos', 'lomas_de_monteverde', 'melipal', 'nueva_esperanza', 'nueva_jamaica', 'nireco', 'omega', 'parque_lago_moreno', 'parques_nacionales', 'peninsula_san_pedro', 'peumayen', 'pinar_del_lago', 'pinar_de_festa', 'playa_bonita', 'playa_serena', 'quimey_hue', 'rancho_grande', 'san_ignacio_del_cerro', 'san_francisco', 'sara_maria_furman', 'valle_azul', 'villa_catedral', 'villa_don_orione', 'villa_lago_gutierrez', 'villa_los_coihues', 'virgen_de_las_nieves', 'virgen_misionera', 'villa_nahuel_malal', 'villa_verde', 'otro', name='barrios_enum'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni'),
    sa.UniqueConstraint('email')
    )
    op.create_table('animales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('especie', sa.String(length=50), nullable=False),
    sa.Column('raza', sa.String(length=100), nullable=True),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('sexo', sa.String(length=10), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('tamanio', sa.String(length=50), nullable=True),
    sa.Column('esta_castrado', sa.Boolean(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('motivo_baja', sa.String(length=100), nullable=True),
    sa.Column('fecha_baja', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('numero_patente', sa.String(length=50), nullable=True),
    sa.Column('fecha_emision_patente', sa.DateTime(), nullable=True),
    sa.Column('fecha_vencimiento_patente', sa.DateTime(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('id_propietario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_propietario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_patente')
    )
    op.create_table('denuncias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('tipo_denuncia', sa.Enum('maltrato_animal', 'abandono', 'perros_sueltos', 'sintomas_rabia', 'mordedura', 'basura_roedores', 'garrapatas', 'animal_muerto', 'fauna_urbana', 'alimentacion_fauna', 'tenencia_ilegal', 'caza_furtiva', 'atropello_fauna', 'veterinarias_ilegales', 'molestias_vecinales', 'emergencia_animal', 'otro', name='tipos_denuncia_enum'), nullable=False),
    sa.Column('barrio', sa.String(length=50), nullable=True),
    sa.Column('detalles_extra', sa.Text(), nullable=True),
    sa.Column('ubicacion', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('noticias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('barrio', sa.String(length=50), nullable=True),
    sa.Column('imagenes', sa.JSON(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('publicado', sa.Boolean(), nullable=True),
    sa.Column('id_admin', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_admin'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reset_password_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('adopciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_animal', sa.Integer(), nullable=False),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('fecha_publicacion', sa.DateTime(), nullable=True),
    sa.Column('disponible', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_animal'], ['animales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('archivos_denuncia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_denuncia', sa.Integer(), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=255), nullable=False),
    sa.Column('ruta_archivo', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id_denuncia'], ['denuncias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fotos_animales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_animal', sa.Integer(), nullable=True),
    sa.Column('public_id', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('es_principal', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_animal'], ['animales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fotos_noticia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_noticia', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('es_principal', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_noticia'], ['noticias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historial_libreta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_animal', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('registrado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_animal'], ['animales.id'], ),
    sa.ForeignKeyConstraint(['registrado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turnos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_animal', sa.Integer(), nullable=False),
    sa.Column('tipo_turno', sa.Enum('castracion_canino_macho', 'castracion_canino_hembra', 'castracion_felino_macho', 'castracion_felino_hembra', 'vacunacion_antirrabica', 'desparasitacion', 'consulta_veterinaria_primaria', 'identificacion_microchip', 'tratamiento_sarna', 'otro', name='tipos_turno_enum'), nullable=False),
    sa.Column('fecha_solicitada', sa.Date(), nullable=False),
    sa.Column('fecha_turno', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('instrucciones', sa.Text(), nullable=True),
    sa.Column('motivo_cancelacion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_animal'], ['animales.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turnos')
    op.drop_table('historial_libreta')
    op.drop_table('fotos_noticia')
    op.drop_table('fotos_animales')
    op.drop_table('archivos_denuncia')
    op.drop_table('adopciones')
    op.drop_table('reset_password_tokens')
    op.drop_table('noticias')
    op.drop_table('denuncias')
    op.drop_table('animales')
    op.drop_table('usuarios')
    op.drop_table('resumen_ia')
    # ### end Alembic commands ###
